language: python

python:
   - "3.5"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install pylint
    - pip install requests

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version

script:
    - date
    - ls -lah
    - make test
<<<<<<< HEAD
=======

>>>>>>> 769c3be519916983f641b77fce0769f2689c2f2e
