"""empty message

Revision ID: a7753a554c71
Revises: None
Create Date: 2016-07-09 17:12:42.253989

"""

# revision identifiers, used by Alembic.
revision = 'a7753a554c71'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seasonName', sa.String(length=250), nullable=False),
    sa.Column('league', sa.String(length=250), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('numTeams', sa.Integer(), nullable=True),
    sa.Column('numGames', sa.Integer(), nullable=True),
    sa.Column('numMatchdays', sa.Integer(), nullable=True),
    sa.Column('curMatchday', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=250), nullable=False),
    sa.Column('logoURL', sa.String(length=250), nullable=True),
    sa.Column('nickname', sa.String(length=250), nullable=True),
    sa.Column('marketVal', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=250), nullable=True),
    sa.Column('time', sa.String(length=250), nullable=True),
    sa.Column('awayTeam', sa.String(length=250), nullable=True),
    sa.Column('homeTeam', sa.String(length=250), nullable=True),
    sa.Column('awayTeamScore', sa.Integer(), nullable=True),
    sa.Column('homeTeamScore', sa.Integer(), nullable=True),
    sa.Column('matchDay', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('nation', sa.String(length=250), nullable=True),
    sa.Column('birth', sa.String(length=250), nullable=True),
    sa.Column('pos', sa.String(length=250), nullable=True),
    sa.Column('jerseyNum', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_team',
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], )
    )
    op.create_table('standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=250), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('matchesPlayed', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('goalsFor', sa.Integer(), nullable=True),
    sa.Column('goalsAgainst', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_game',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game')
    op.drop_table('standing')
    op.drop_table('season_team')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('team')
    op.drop_table('season')
    ### end Alembic commands ###
